# Generated by Django 5.0.2 on 2024-02-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_loguser_logentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='User',
            new_name='user',
        ),
    ]
