# Generated by Django 5.0.2 on 2024-02-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_logentry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name_plural': 'LogEntries'},
        ),
    ]
